config/routes.rb
Rails.application.routes.draw do
  resources :notes do
    patch :update_row_order, on: :collection
    member do
      patch 'update_complete'
    end
  end

  root 'notes#index'

end

app/models/note.rb
class Note < ActiveRecord::Base
  include RankedModel
  ranks :row_order
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session,
      if: Proc.new { |c| c.request.format =~ %r{application/json} }
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :update_complete, :destroy]

  def index
    @notes = Note.rank(:row_order).all
  end

  def update_row_order
    @note = Note.find_by_id(params[:id])
    Note.update(@note.id, row_order: params[:row_order])

    render nothing: true # this is a POST action, updates sent via AJAX, no view rendered
  end

  def new
    @note = Note.new
  end

  def edit
  end

  def create
    @note = Note.new(note_params)
    if @note.save
      redirect_to notes_path
    end
  end

  def update
    if @note.update(note_params)
      redirect_to notes_path, notice: 'Note was successfully updated.'
    else
      render :edit
    end
  end

  def update_complete
    Note.update(@note.id, complete: params[:complete])
  end

  def destroy
    @note.destroy
    redirect_to notes_path, notice: 'Note was successfully deleted.'
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:title, :description,
                                 :complete, :due_on, :row_order)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p id="notice"><%= notice %></p>
<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :row_order, :value => 999 %>
  </div>
  <div class="field">
    <%= f.label :complete %><br>
    <%= f.check_box :complete %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :due_on %><br>
    <%= f.datetime_select :due_on, ampm: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/create.html.erb
<h1>Notes#create</h1>
<p>Find me in app/views/notes/create.html.erb</p>

app/views/notes/destroy.html.erb
<h1>Notes#destroy</h1>
<p>Find me in app/views/notes/destroy.html.erb</p>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>To Do List</h1>

<table class="table table-bordered table-striped" id="sortable">
  <thead>
    <tr>
      <th>
        Note
      </th>
      <th>
        Details
      </th>
      <th>
        Due On
      </th>
      <th>
        Complete - Edit - Delete
      </th>
    </tr>
  </thead>
  <tbody>
    <% @notes.each do |note| %>
      <%= form_for note do |f|%>
      <tr data-item-id=<%= "#{note.id}" %> class="item">
        <td>
          <%= note.title %>
        </td>
        <td>
          <%= note.description %>
        </td>
        <td>
          <%= note.due_on.strftime("%a-%b-%d%l:%M%p") if note.due_on %>
        </td>
        <td>
          <%= f.hidden_field :id, class: "rails-id" %>
          <%=f.check_box :complete, class: "complete_checkboxes" %>
          <%= link_to 'Delete', note, method: :delete, data: { confirm:
              'Are you sure?' }, :class => 'btn btn-default pull-right' %>
          <%= link_to 'Edit', edit_note_path(note), :class =>
              'btn btn-default pull-right' %>
        </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>Create a new Note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/update.html.erb
<h1>Notes#update</h1>
<p>Find me in app/views/notes/update.html.erb</p>